name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        target: [ESP32CommandStation, ESP32CommandStation-pcb]
    steps:
    - name: Checkout ESP32CommandStation
      uses: actions/checkout@v2
    - name: Update config For CS PCB
      if: ${{ matrix.target == 'ESP32CommandStation-pcb' }}
      uses: DamianReeves/write-file-action@master
      with:
        path: sdkconfig.defaults
        contents: |
          CONFIG_ESP32CS_FORCE_FACTORY_RESET_PIN=34
          CONFIG_WIFI_MODE_SOFTAP=y
          CONFIG_OPS_HBRIDGE_LMD18200=y
          CONFIG_OPS_HBRIDGE_ENABLE_PIN=4
          CONFIG_OPS_HBRIDGE_SIGNAL_PIN=17
          CONFIG_OPS_HBRIDGE_BRAKE_PIN=26
          CONFIG_OPS_DCC_PREAMBLE_BITS=16
          CONFIG_OPS_ADC_CHANNEL_0=y
          CONFIG_OPS_RAILCOM=y
          CONFIG_OPS_RAILCOM_ENABLE_PIN=12
          CONFIG_OPS_RAILCOM_UART2=y
          CONFIG_OPS_RAILCOM_UART=2
          CONFIG_OPS_RAILCOM_UART_RX_PIN=33
          CONFIG_OPS_RAILCOM_FEEDBACK_QUEUE=10
          CONFIG_PROG_HBRIDGE_DRV880X=y
          CONFIG_PROG_HBRIDGE_ENABLE_PIN=18
          CONFIG_PROG_HBRIDGE_SIGNAL_PIN=19
          CONFIG_PROG_ADC_CHANNEL_3=y
          CONFIG_LCC_CAN_RX_PIN=27
          CONFIG_LCC_CAN_TX_PIN=32
          CONFIG_STATUS_LED=y
          CONFIG_STATUS_LED_DATA_PIN=22
          CONFIG_STATUS_LED_TYPE_APA106=y
          CONFIG_GPIO_OUTPUTS=n
          CONFIG_GPIO_SENSORS=n
          CONFIG_GPIO_S88=n
          CONFIG_DISPLAY_SCL=21
          CONFIG_DISPLAY_SDA=23
          CONFIG_THERMALMONITOR=y
          CONFIG_THERMALMONITOR_TYPE_MCP9701=y
          CONFIG_THERMALMONITOR_ZERO_MV=400
          CONFIG_THERMALMONITOR_MV_PER_C=195
          CONFIG_THERMALMONITOR_ADC_CHANNEL_7=y
        write-mode: append
    - name: Build
      uses: atanisoft/esp-idf-ci-action@master
      with:
        path: .
    - name: Prepare Binaries
      run: |
        mkdir -p binaries
        cp .github/firmwarereadme.txt binaries/readme.txt
        cp build/ESP32CommandStation.bin binaries
        cp build/partition_table/partition-table.bin binaries
        cp build/ota_data_initial.bin binaries
        cp build/bootloader/bootloader.bin binaries
    - name: Package binaries
      uses: actions/upload-artifact@v1
      with:
        name: ${{ matrix.target }}
        path: binaries
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
