name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Build
        uses: georgik/esp-idf-ci-action@branch-release-v4.3
        with:
          path: firmware
      - name: Prepare Binaries
        run: |
          mkdir -p binaries
          cp .github/firmwarereadme.txt binaries/readme.txt
          cp firmware/build/ESP32CommandStation.bin binaries
          cp firmware/build/partition_table/partition-table.bin binaries
          cp firmware/build/ota_data_initial.bin binaries
          cp firmware/build/bootloader/bootloader.bin binaries
      - name: Package binaries
        uses: actions/upload-artifact@v1
        with:
          name: ESP32CommandStation
          path: binaries
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}